tasks:
  - name: Render TYPO3 docs
    command: |
      vendor/bin/guides render Documentation public && \
      python3 -m http.server --directory public 8000

ports:
  - port: 8000
    onOpen: open-preview
